### ISSUE TITLE
Issue with Parallax being recognized as Deadlift

### ISSUE THREAD

**Issue by Rapthera** [scttcper/honbot-server#13]
Not sure whether to submit this issue under the client / server.

Deadlift is being recognized as Parallax, I assume you've mixed up the hero ID's somehow.

http://i.imgur.com/L4spknt.png

**Comment by scttcper** [comment]
The current honbot.com is no longer maintained. http://beta.honbot.com/match/138840256/ is working correctly. Thanks for the report though, was good to check if the new version was correct.

**Comment by Rapthera** [comment]
Any plans to push beta to uh, not beta?

first time i've come across the beta since it wasn't mentioned anywhere on honbot itself.

**Comment by scttcper** [comment]
Soon. Features aren't quite there yet.
