### ISSUE TITLE
Parallax - comes up as Deadlift

### ISSUE THREAD

**Issue by hoxbug** [scttcper/honbot-server#14]
Hello, don't know if this is the right place to say this but, parallax shows as deadlift, name and icon are those of deadlift. Thank you

**Comment by kroy** [comment]
Hey, someone reported this before (#13). Basically, all development is happening on http://beta.honbot.com/ and the issue should be fixed there.

**Comment by scttcper** [comment]
@kroy is correct. Thanks guys.
