### ISSUE TITLE
Add more information to player page

### ISSUE THREAD

**Issue by scttcper** [scttcper/honbot-server#9]
Try getting straight from master server available from http://masterserver.hon.s2games.com/client_requester.php?f=show_stats&nickname=sisterfister&table=ranked 

http://masterserver.cis.heroesofnewerth.com/client_requester.php?f=show_stats&nickname=testie&table=ranked

**Comment by scttcper** [comment]
http://masterserver.naeu.heroesofnewerth.com/client_requester.php?f=nick2id&nickname[0]=stridex

**Comment by andypoorman** [comment]
I know this is outdated but what are you looking for?

**Comment by scttcper** [comment]
At the time I think I was looking at the favorite heroes, but decided against querying master server.
